name: solr-cluster

services:
  solr1:
    container_name: solr1
    depends_on:
      - zoo1
    environment:
      - ZK_HOST=zoo1:${ZK_PORT}
      - SOLR_HOST=solr1
      - SOLR_PORT=${SOLR_PORT}
      - VERBOSE=true
    image: solr:${SOLR_VERSION}
    networks:
      - solr
    ports:
      - "${SOLR_PORT}:${SOLR_PORT}"
    restart: unless-stopped
    volumes:
      - ./solr/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - solr1_data:/var/solr
      
  zoo1:
    container_name: zoo1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;${ZK_PORT}
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    hostname: zoo1
    image: zookeeper:${ZK_VERSION}
    networks:
      - solr
    ports:
      - "${ZK_PORT}:${ZK_PORT}"
      - 7001:7000
    restart: unless-stopped
    volumes:
      - zoo1_data:/data

networks:
  solr:

volumes:
  solr1_data:
  zoo1_data:
