name: solr-cluster

services:
  solr1:
    container_name: solr1
    depends_on:
      - zoo1
    environment:
      - ZK_HOST=zoo1:2181
      - SOLR_HOST=solr1
      - SOLR_PORT=8981
      - VERBOSE=true
    image: solr:8.11.1
    networks:
      - solr
    ports:
     - "8981:8981"
    restart: unless-stopped
    volumes:
      - ./solr/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - solr1_data:/var/solr
      
  zoo1:
    container_name: zoo1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    hostname: zoo1
    image: zookeeper:3.8.0
    networks:
      - solr
    ports:
      - 2181:2181
      - 7001:7000
    restart: unless-stopped
    volumes:
      - zoo1_data:/data

networks:
  solr:

volumes:
  solr1_data:
  zoo1_data:
